homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_el
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# change the default stuff cause some of it is not used

# custom stuff
shopping_list:
python_script:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: 192.168.178.73:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:

# Sensors
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: load_15m
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postal_code
    street_number: !secret street_number
  - platform: command_line
    name: shopping_list_items
    command: "jq '.[] | select(.complete==false) | .name' .shopping_list.json "

wake_on_lan:
system_health:
media_extractor:
  default_query: best

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_boolean:
  waste_moved:
    name: Waste has been moved
    initial: 'off'
    icon: mdi:delete-empty


webostv:
  name: TV
  host: !secret tv_url
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret tv_mac
  customize:
    sources:
      - "Streambox"
      - "Decoder"
      - "Pc"
      - "YouTube"
      - "Netflix"
      - "Spotify: muziek en podcasts"
      - "Amazon Prime Video"
      - "Disney+"

matrix:
  homeserver: !secret matrix_homeserver
  username: !secret matrix_username
  password: !secret matrix_password
  rooms:
    - !secret matrix_home_room
    - !secret matrix_test_room
  commands:
    - word: sl
      name: get_shopping_list
    - expression: "[Aa]dd (?P<item>.*) to shopping list"
      name: add_shopping_list_item
  
notify:
  - name: matrix_home
    platform: matrix
    default_room: !secret matrix_home_room
