homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_el
  external_url: !secret base_url
  # metric for Metric, imperial for Imperial
  unit_system: metric
  country: NL
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - '/config/downloads'
    - '/config/www'

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# custom stuff
#lovelace: !include lovelace/lovelace.yaml
lovelace:
  mode: storage

frontend:
  themes: !include_dir_merge_named themes

shopping_list:
python_script:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.1.200

# Sensors
sensor: !include_dir_list sensors

wake_on_lan:
system_health:
media_extractor:
  default_query: best

automation: !include_dir_list automations
binary_sensor: !include_dir_list binary_sensors
cover: !include_dir_list covers
group: !include groups.yaml
input_boolean: !include_dir_named input_boolean
input_number: !include_dir_named input_number
input_text: !include_dir_named input_text
light: !include_dir_list lights
scene: !include_dir_list scenes
script: !include_dir_named scripts
switch: !include_dir_list switches

# integrations
notify: !include_dir_list integrations/notify
utility_meter: !include_dir_named integrations/utility_meter
proxmoxve: !include_dir_list integrations/proxmoxve
matrix: !include integrations/matrix.yaml
influxdb: !include integrations/influxdb.yaml

downloader:
  download_dir: downloads

logger:
  default: critical

google_assistant:
  project_id: 32098
  service_account: !include google_project.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
