title: Home
views:
  - badges:
      - entity: person.tim
      - entity: person.sabine
    cards:
      - type: custom:lg-remote-control
        entity: media_player.tv
      - theme: default
        title: Shopping list
        type: shopping-list
      - type: media-control
        entity: media_player.chromecast
      - type: entities
        entities:
          - sensor.afvalwijzer_gft
          - sensor.afvalwijzer_papier
          - sensor.afvalwijzer_plastic
          - sensor.afvalwijzer_restafval
          - input_boolean.waste_moved
        title: Trash
      - type: button
        entity: timer.laundry
        icon: mdi:washing-machine
        name: Start laundry timer
        show_state: true
        tap_action:
          action: call-service
          service: timer.start
          service_data:
            duration: '4800'
          target:
            entity_id: timer.laundry
        hold_action:
          action: call-service
          service: timer.cancel
          service_data: {}
          target:
            entity_id: timer.laundry
      - type: entities
        entities:
          - input_number.laundry_slider
    path: default_view
    title: Home
  - title: Statistics
    path: statistics
    badges: []
    cards:
      - type: glance
        entities:
          - entity: sensor.solaredge_current_power
          - entity: sensor.solaredge_energy_today
          - entity: sensor.solaredge_energy_this_month
          - entity: sensor.solaredge_lifetime_energy
        title: Solar
        columns: 2
      - type: entities
        entities:
          - sensor.dsmr_consumption_gas_currently_delivered
          - sensor.dsmr_reading_electricity_currently_delivered
          - sensor.dsmr_reading_electricity_currently_returned
      - type: custom:power-wheel-card
        solar_power_entity: sensor.solaredge_current_power_kwh
        grid_power_consumption_entity: sensor.dsmr_reading_electricity_currently_delivered
        grid_power_production_entity: sensor.dsmr_reading_electricity_currently_returned
        power_decimals: 3
      - type: weather-forecast
        entity: weather.openweathermap
      - type: light
        entity: light.woonkamer
