id: 'releases_ntfy'
alias: Notify github releases
description: ""
trigger:
  - platform: event
    event_type: feedreader
    event_data: {}
condition: []
action:
  - service: notify.ntfy_releases
    data:
      message: "{{ trigger.event.data.link }}"
      title: "{{ trigger.event.data.title }}"
  - service: todo.add_item
    data:
      item: '{{ trigger.event.data.link }}'
    target:
      entity_id: todo.updates
mode: queued
