id: 'releases_ntfy'
alias: Notify github releases
description: ""
trigger:
  - platform: event
    event_type: feedreader
    event_data: {}
condition: []
action:
  - service: notify.ntfy_releases
    data:
      message: "{{ trigger.event.data.summary }}"
      title: "{{ trigger.event.data.title }}"
mode: queued
