alias: Vacuum Going Home
id: 'vacuum_notifications'
trigger:
  - platform: state
    entity_id: vacuum.roborock_vacuum_a38
    to: "Cleaning"
    for: "00:01:00"
  - platform: state
    entity_id: vacuum.roborock_vacuum_a38
    to: "Docked"
    for: "00:01:00"
  - platform: state
    entity_id: vacuum.roborock_vacuum_a38
    to: "Error"
    for: "00:01:00"
action:
  - service: notify.matrix_home
    data:
      title: "Hello from George!"
      message: >
        Hello from George! My state changed from {{ trigger.from_state.state }}
        to {{ trigger.to_state.state }}!
