alias: Waste has not been moved
trigger:
  platform: time_pattern
  hours: "/1"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.waste_moved
      state: 'off'
    - condition: time
      after: '18:00:00'
      before: '23:00:00'
    - condition: template
      value_template: "{{ states('sensor.afvalwijzer_tomorrow') != 'Geen' }}"
action:
  - service: notify.matrix_home
    data:
      title: "Trash"
      message: 'Tomorrow is trash day! Trash type {{ states.sensor.afvalwijzer_tomorrow.state }} will be picked up.'
  - service: notify.mobile_app_fp4
    data:
      title: "Trash"
      message: 'Tomorrow is trash day! Trash type {{ states.sensor.afvalwijzer_tomorrow.state }} will be picked up.'
